// Zmockowane dane budżetu — nie wymaga backendu ani API

export const mockBudgetData = {
  '2025-02': {
    totalIncome: 7500,
    totalExpenses: 5980,
    net: 1520,
    savingsRate: 20.3,
    transactionCount: 21,
    categoryBreakdown: [
      {
        categoryId: 1,
        categoryName: 'Wynagrodzenie',
        categoryIcon: '💼',
        categoryColor: '#10B981',
        income: 7500,
        expenses: 0,
        net: 7500,
        transactionCount: 1,
      },
      {
        categoryId: 2,
        categoryName: 'Żywność',
        categoryIcon: '🛒',
        categoryColor: '#F59E0B',
        income: 0,
        expenses: 1350,
        net: -1350,
        transactionCount: 9,
      },
      {
        categoryId: 3,
        categoryName: 'Transport',
        categoryIcon: '🚌',
        categoryColor: '#3B82F6',
        income: 0,
        expenses: 420,
        net: -420,
        transactionCount: 4,
      },
      {
        categoryId: 4,
        categoryName: 'Mieszkanie',
        categoryIcon: '🏠',
        categoryColor: '#8B5CF6',
        income: 0,
        expenses: 2800,
        net: -2800,
        transactionCount: 3,
      },
      {
        categoryId: 5,
        categoryName: 'Rozrywka',
        categoryIcon: '🎬',
        categoryColor: '#EC4899',
        income: 0,
        expenses: 680,
        net: -680,
        transactionCount: 4,
      },
      {
        categoryId: 6,
        categoryName: 'Zdrowie',
        categoryIcon: '💊',
        categoryColor: '#EF4444',
        income: 0,
        expenses: 730,
        net: -730,
        transactionCount: 0,
      },
    ],
  },

  '2025-03': {
    totalIncome: 9200,
    totalExpenses: 5410,
    net: 3790,
    savingsRate: 41.2,
    transactionCount: 26,
    categoryBreakdown: [
      {
        categoryId: 1,
        categoryName: 'Wynagrodzenie',
        categoryIcon: '💼',
        categoryColor: '#10B981',
        income: 7500,
        expenses: 0,
        net: 7500,
        transactionCount: 1,
      },
      {
        categoryId: 7,
        categoryName: 'Freelance',
        categoryIcon: '💻',
        categoryColor: '#06B6D4',
        income: 1700,
        expenses: 0,
        net: 1700,
        transactionCount: 2,
      },
      {
        categoryId: 2,
        categoryName: 'Żywność',
        categoryIcon: '🛒',
        categoryColor: '#F59E0B',
        income: 0,
        expenses: 1180,
        net: -1180,
        transactionCount: 8,
      },
      {
        categoryId: 3,
        categoryName: 'Transport',
        categoryIcon: '🚌',
        categoryColor: '#3B82F6',
        income: 0,
        expenses: 380,
        net: -380,
        transactionCount: 5,
      },
      {
        categoryId: 4,
        categoryName: 'Mieszkanie',
        categoryIcon: '🏠',
        categoryColor: '#8B5CF6',
        income: 0,
        expenses: 2800,
        net: -2800,
        transactionCount: 3,
      },
      {
        categoryId: 5,
        categoryName: 'Rozrywka',
        categoryIcon: '🎬',
        categoryColor: '#EC4899',
        income: 0,
        expenses: 350,
        net: -350,
        transactionCount: 4,
      },
      {
        categoryId: 6,
        categoryName: 'Zdrowie',
        categoryIcon: '💊',
        categoryColor: '#EF4444',
        income: 0,
        expenses: 700,
        net: -700,
        transactionCount: 3,
      },
    ],
  },

  '2025-04': {
    totalIncome: 8500,
    totalExpenses: 5230,
    net: 3270,
    savingsRate: 38.5,
    transactionCount: 24,
    categoryBreakdown: [
      {
        categoryId: 1,
        categoryName: 'Wynagrodzenie',
        categoryIcon: '💼',
        categoryColor: '#10B981',
        income: 7500,
        expenses: 0,
        net: 7500,
        transactionCount: 1,
      },
      {
        categoryId: 7,
        categoryName: 'Freelance',
        categoryIcon: '💻',
        categoryColor: '#06B6D4',
        income: 1000,
        expenses: 0,
        net: 1000,
        transactionCount: 1,
      },
      {
        categoryId: 2,
        categoryName: 'Żywność',
        categoryIcon: '🛒',
        categoryColor: '#F59E0B',
        income: 0,
        expenses: 1240,
        net: -1240,
        transactionCount: 10,
      },
      {
        categoryId: 3,
        categoryName: 'Transport',
        categoryIcon: '🚌',
        categoryColor: '#3B82F6',
        income: 0,
        expenses: 290,
        net: -290,
        transactionCount: 3,
      },
      {
        categoryId: 4,
        categoryName: 'Mieszkanie',
        categoryIcon: '🏠',
        categoryColor: '#8B5CF6',
        income: 0,
        expenses: 2800,
        net: -2800,
        transactionCount: 3,
      },
      {
        categoryId: 5,
        categoryName: 'Rozrywka',
        categoryIcon: '🎬',
        categoryColor: '#EC4899',
        income: 0,
        expenses: 480,
        net: -480,
        transactionCount: 4,
      },
      {
        categoryId: 6,
        categoryName: 'Zdrowie',
        categoryIcon: '💊',
        categoryColor: '#EF4444',
        income: 0,
        expenses: 420,
        net: -420,
        transactionCount: 3,
      },
    ],
  },

  '2025-05': {
    totalIncome: 7500,
    totalExpenses: 6100,
    net: 1400,
    savingsRate: 18.7,
    transactionCount: 19,
    categoryBreakdown: [
      {
        categoryId: 1,
        categoryName: 'Wynagrodzenie',
        categoryIcon: '💼',
        categoryColor: '#10B981',
        income: 7500,
        expenses: 0,
        net: 7500,
        transactionCount: 1,
      },
      {
        categoryId: 2,
        categoryName: 'Żywność',
        categoryIcon: '🛒',
        categoryColor: '#F59E0B',
        income: 0,
        expenses: 1400,
        net: -1400,
        transactionCount: 7,
      },
      {
        categoryId: 3,
        categoryName: 'Transport',
        categoryIcon: '🚌',
        categoryColor: '#3B82F6',
        income: 0,
        expenses: 310,
        net: -310,
        transactionCount: 3,
      },
      {
        categoryId: 4,
        categoryName: 'Mieszkanie',
        categoryIcon: '🏠',
        categoryColor: '#8B5CF6',
        income: 0,
        expenses: 2800,
        net: -2800,
        transactionCount: 3,
      },
      {
        categoryId: 5,
        categoryName: 'Rozrywka',
        categoryIcon: '🎬',
        categoryColor: '#EC4899',
        income: 0,
        expenses: 920,
        net: -920,
        transactionCount: 3,
      },
      {
        categoryId: 6,
        categoryName: 'Zdrowie',
        categoryIcon: '💊',
        categoryColor: '#EF4444',
        income: 0,
        expenses: 670,
        net: -670,
        transactionCount: 2,
      },
    ],
  },
};
